notification:
  chat:
     enabled: true
     #Delay after joining
     delay: 20
     #Repeat after first run, 0 to disable.
     repeat: 300
  bossbar:
     enabled: true
     delay: 1
     repeat: 60
     duration: 15
     color: blue
  actionbar:
     enabled: true
     delay: 1
     repeat: 60
     duration: 10
